### ISSUE TITLE
post_upload: Release a new version to pick up #44

### ISSUE THREAD

**Issue by edmorley** [mozilla-services/product-delivery-tools#45]
I don't suppose a new version of post_upload could be released so we can use the change in #44 in [bug 1281644](https://bugzilla.mozilla.org/show_bug.cgi?id=1281644)?

Many thanks :-)

**Comment by oremj** [comment]
I'll plan on doing this Wednesday (8/10) @ 1pm

**Comment by nthomas-mozilla** [comment]
Could you please drop a comment in #releng when deploying. Thanks.

**Comment by oremj** [comment]
The production tools have been updated to reflect #44.
